### PR TITLE
adding matplotlib and the ability to see plots inline

### PR DESCRIPTION
**Pull request by livbuli**
@adamhajari Issue with notebook, here is the solution, here is what the solution affects.

### CODE REVIEW

**Comment by adamhajari** [comment]
@livbuli are you sure the import matplotlib is necessary? I don't think this module uses that library directly.

**Comment by livbuli** [comment]
I was under the impression that I needed to import matplotlib to view plots inline? (as well as add %matplotlib inline?) But either way, discovered that the order of operations needs to be switched in order for plots to work properly. Let me make the edit and and then do another PR. Thanks!

**Comment by livbuli** [comment]
also @adamhajari thoughts on whether we should add an explanation as to why we %matplotlib inline is necessary in that first explainer paragraph?

**Comment by adamhajari** [comment]
@livbuli yes on an explanation for why we're adding `%matplotlib inline`, but maybe add it as an in line comment

**Pull request merged**
